<?php
$mediaProCache = 'a:50:{i:0;a:7:{s:2:"id";s:1:"3";s:5:"title";s:8:"Facebook";s:7:"website";s:19:"http://www.facebook";s:10:"regexmatch";s:62:"http://www\.facebook\.com/video/video\.php\?v=([\w]+)&*[\w;=]*";s:9:"embedcode";s:394:"<object width="640" height="385" > 
       <param name="allowfullscreen" value="true" /> 
       <param name="allowscriptaccess" value="always" /> 
       <param name="movie" value="http://www.facebook.com/v/$1" /> 
       <embed src="http://www.facebook.com/v/$1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="640" height="385"></embed></object>";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:1;a:7:{s:2:"id";s:1:"2";s:5:"title";s:8:"Metacafe";s:7:"website";s:23:"http://www.metacafe.com";s:10:"regexmatch";s:62:"http://www\.metacafe\.com/watch/([\w-]+/[\w_]*)[\w&;=\+_\-\/]*";s:9:"embedcode";s:220:"<embed src="http://www.metacafe.com/fplayer/$1.swf" width="540" height="334" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent"></embed>";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:2;a:7:{s:2:"id";s:1:"1";s:5:"title";s:7:"Youtube";s:7:"website";s:22:"http://www.youtube.com";s:10:"regexmatch";s:87:"http://[\w.]+youtube\.[\w]+/watch[\?\#!]+v=([\w-]+)[\w&;+=-]*[\#t=]*([\d]*)[&;10shdq=]*";s:9:"embedcode";s:342:"<object width="640" height="385">
<param name="movie" value="http://www.youtube.com/v/$1&fs=1&start=$2"></param>
<param name="allowFullScreen" value="true"></param>
<embed src="http://www.youtube.com/v/$1&fs=1&start=$2" type="application/x-shockwave-flash" allowfullscreen="true" width="640" height="385" wmode="transparent"></embed></object>";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:3;a:7:{s:2:"id";s:1:"4";s:5:"title";s:5:"Vimeo";s:7:"website";s:20:"http://www.vimeo.com";s:10:"regexmatch";s:45:"http://[w\.]*vimeo\.com/([\d]+)[\w&;=\?+%/-]*";s:9:"embedcode";s:423:"<object type="application/x-shockwave-flash" width="640" height="385" data="http://vimeo.com/moogaloop.swf?clip_id=$1&amp;server=vimeo.com&amp;fullscreen=1&amp;video_info=1">	<param name="quality" value="best"><param name="allowfullscreen" value="true"><param name="scale" value="showAll"><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=$1&amp;server=vimeo.com&amp;fullscreen=1&amp;video_info=1"></object>";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:4;a:7:{s:2:"id";s:1:"5";s:5:"title";s:13:"College Humor";s:7:"website";s:27:"http://www.collegehumor.com";s:10:"regexmatch";s:53:"http://]*[a-z]*?[\.]?collegehumor\.com/video:([0-9]+)";s:9:"embedcode";s:161:"<embed src="http://www.collegehumor.com/moogaloop/moogaloop.swf?clip_id=$1" quality="best" width="640" height="385" type="application/x-shockwave-flash"></embed>";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:5;a:7:{s:2:"id";s:1:"6";s:5:"title";s:12:"Google Video";s:7:"website";s:23:"http://video.google.com";s:10:"regexmatch";s:69:"[http://]*video\.google\.[\w.]+/videoplay\?docid=([-\d]+)[&\w;=\+.-]*";s:9:"embedcode";s:196:"<embed style="width:640px; height:385px;" id="VideoPlayback" type="application/x-shockwave-flash" src="http://video.google.com/googleplayer.swf?docId=$1" flashvars="" wmode="transparent"> </embed>";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:6;a:7:{s:2:"id";s:1:"7";s:5:"title";s:4:"Veoh";s:7:"website";s:19:"http://www.veoh.com";s:10:"regexmatch";s:44:"http://www\.veoh\.com/(.*)/watch/([A-Z0-9]*)";s:9:"embedcode";s:727:"<object width="410" height="341" id="veohFlashPlayer" name="veohFlashPlayer"><param name="movie" value="http://www.veoh.com/static/swf/webplayer/WebPlayer.swf?version=AFrontend.5.5.2.1066&permalinkId=$2&player=videodetailsembedded&videoAutoPlay=0&id=anonymous"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.veoh.com/static/swf/webplayer/WebPlayer.swf?version=AFrontend.5.5.2.1066&permalinkId=$2&player=videodetailsembedded&videoAutoPlay=0&id=anonymous" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="410" height="341" id="veohFlashPlayerEmbed" name="veohFlashPlayerEmbed"></embed></object>";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:7;a:7:{s:2:"id";s:1:"8";s:5:"title";s:5:"Youku";s:7:"website";s:20:"http://www.youku.com";s:10:"regexmatch";s:55:"http://([A-Z0-9]*).youku.com/v_show/id_([A-Z0-9]*).html";s:9:"embedcode";s:193:"
<embed src="http://player.youku.com/player.php/sid/$2/v.swf" quality="high" width="480" height="400" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash"></embed>";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:8;a:7:{s:2:"id";s:1:"9";s:5:"title";s:9:"USteam.tv";s:7:"website";s:21:"http://www.ustream.tv";s:10:"regexmatch";s:47:"http://([A-Z0-9]*).ustream.tv/recorded/([0-9]*)";s:9:"embedcode";s:685:"
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="480" height="386" id="utv159159" name="utv_n_278276"><param name="flashvars" value="beginPercent=0.4193&amp;endPercent=0.4316&amp;autoplay=false&locale=en_US" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="src" value="http://www.ustream.tv/flash/video/$2" /><embed flashvars="beginPercent=0.4193&amp;endPercent=0.4316&amp;autoplay=false&locale=en_US" width="480" height="386" allowfullscreen="true" allowscriptaccess="always" id="utv159159" name="utv_n_278276" src="http://www.ustream.tv/flash/video/$2" type="application/x-shockwave-flash" /></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:9;a:7:{s:2:"id";s:2:"10";s:5:"title";s:6:"Rutube";s:7:"website";s:16:"http://rutube.ru";s:10:"regexmatch";s:55:"http://rutube.ru/tracks/([A-Z0-9]*).html\?v=([A-Z0-9]*)";s:9:"embedcode";s:348:"
<OBJECT width="470" height="353"><PARAM name="movie" value="http://video.rutube.ru/$2"></PARAM><PARAM name="wmode" value="window"></PARAM><PARAM name="allowFullScreen" value="true"></PARAM><EMBED src="http://video.rutube.ru/$2" type="application/x-shockwave-flash" wmode="window" width="470" height="353" allowFullScreen="true" ></EMBED></OBJECT>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:10;a:7:{s:2:"id";s:2:"11";s:5:"title";s:7:"Novamov";s:7:"website";s:22:"http://www.novamov.com";s:10:"regexmatch";s:40:"http://www.novamov.com/video/([A-Z0-9]*)";s:9:"embedcode";s:166:"
<iframe style="overflow: hidden; border: 0; width: 600px; height: 480px" src="http://embed.novamov.com/embed.php?width=600&height=480&v=$1" scrolling="no"></iframe>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:11;a:7:{s:2:"id";s:2:"12";s:5:"title";s:10:"MyVideo.de";s:7:"website";s:21:"http://www.MyVideo.de";s:10:"regexmatch";s:44:"http://www.myvideo.de/watch/([A-Z0-9]*)/(.*)";s:9:"embedcode";s:415:"
<object style="width:470px;height:285px;" width="470" height="285"><param name="movie" value="http://www.myvideo.de/movie/$1"></param><param name="AllowFullscreen" value="true"></param><param name="AllowScriptAccess" value="always"></param><embed src="http://www.myvideo.de/movie/$1" width="470" height="285" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true"></embed></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:12;a:7:{s:2:"id";s:2:"13";s:5:"title";s:8:"LiveLeak";s:7:"website";s:23:"http://www.liveleak.com";s:10:"regexmatch";s:36:"http://www.liveleak.com/view\?i=(.*)";s:9:"embedcode";s:384:"
<object width="450" height="370"><param name="movie" value="http://www.liveleak.com/e/$1"></param><param name="wmode" value="transparent"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.liveleak.com/e/8ee_1281467692" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" width="450" height="370"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:13;a:7:{s:2:"id";s:2:"14";s:5:"title";s:9:"Sevenload";s:7:"website";s:24:"http://www.sevenload.com";s:10:"regexmatch";s:56:"http://([A-Z0-9]*).sevenload.com/videos/([A-Z0-9]*)-(.*)";s:9:"embedcode";s:297:"
<object type="application/x-shockwave-flash" data="http://$1.sevenload.com/pl/$2/500x408/swf" width="500" height="408"><param name="allowFullscreen" value="true" /><param name="allowScriptAccess" value="always" /><param name="movie" value="http://$1.sevenload.com/pl/$2/500x408/swf" /></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:14;a:7:{s:2:"id";s:2:"15";s:5:"title";s:12:"Gametrailers";s:7:"website";s:27:"http://www.gametrailers.com";s:10:"regexmatch";s:51:"http://www.gametrailers.com/video/(.*)/([0-9]*)(.*)";s:9:"embedcode";s:773:"
<<div style="width: 480px;">
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" id="gtembed" width="480" height="392">	<param name="allowScriptAccess" value="sameDomain" /> <param name="allowFullScreen" value="true" /> <param name="movie" value="http://www.gametrailers.com/remote_wrap.php?mid=$2"/><param name="quality" value="high" /> <embed src="http://www.gametrailers.com/remote_wrap.php?mid=$2" swLiveConnect="true" name="gtembed" align="middle" allowScriptAccess="sameDomain" allowFullScreen="true" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="480" height="392"></embed> </object>
</div>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:15;a:7:{s:2:"id";s:2:"16";s:5:"title";s:14:"Funnyordie.com";s:7:"website";s:25:"http://www.funnyordie.com";s:10:"regexmatch";s:49:"http://www.funnyordie.com/videos/([A-Z0-9]*)/(.*)";s:9:"embedcode";s:584:"
<object width="480" height="400" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="ordie_player_$1"><param name="movie" value="http://player.ordienetworks.com/flash/fodplayer.swf" /><param name="flashvars" value="key=$1" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always"></param><embed width="480" height="400" flashvars="key=$1" allowfullscreen="true" allowscriptaccess="always" quality="high" src="http://player.ordienetworks.com/flash/fodplayer.swf" name="ordie_player_$1" type="application/x-shockwave-flash"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:16;a:7:{s:2:"id";s:2:"17";s:5:"title";s:5:"Mevio";s:7:"website";s:20:"http://www.mevio.com";s:10:"regexmatch";s:62:"http://www.mevio.com/channels/\?cId=([0-9]*)\&amp;mId=([0-9]*)";s:9:"embedcode";s:1273:"
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="600" height="336" id="MevioWM" align="middle"><param name="allowScriptAccess" value="never" /><param name="allowFullScreen" value="true" /><param name="movie" value="http://ui.mevio.com/widgets/mwm/MevioWM.swf?r=36745 " /><param name="quality" value="high" /><param name="FlashVars"     value="distribConfig=http://www.mevio.com/widgets/configFiles/distribconfig_mwm_pcw_default.php?r=36745&autoPlay=false&container=false&rssFeed=/%3FcId=$1%26cMediaId=$2%26format=json&playerIdleEnabled=false&fwSiteSection=DistribGeneric" /><param name="bgcolor" value="#000000" />	<embed src="http://ui.mevio.com/widgets/mwm/MevioWM.swf?r=36745 " quality="high" bgcolor="#000000"width="600" height="336" FlashVars="distribConfig=http://www.mevio.com/widgets/configFiles/distribconfig_mwm_pcw_default.php?r=36745&autoPlay=false&container=false&rssFeed=/%3FcId=$1%26cMediaId=$2%26format=json&playerIdleEnabled=false&fwSiteSection=DistribGeneric"name="MevioWM"align="middle"allowScriptAccess="never"allowFullScreen="true"type="application/x-shockwave-flash"pluginspage="http://www.macromedia.com/go/getflashplayer" /></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:17;a:7:{s:2:"id";s:2:"18";s:5:"title";s:7:"Crackle";s:7:"website";s:22:"http://www.crackle.com";s:10:"regexmatch";s:43:"http://www.crackle.com/c/(.*)/(.*)/([0-9]*)";s:9:"embedcode";s:374:"
<embed src="http://www.crackle.com/p/$1/$2.swf?id=$3&mu=0&ap=0" quality="high" bgcolor="#869ca7" width="500" height="281" name="mtgPlayer" align="middle" play="true" loop="false" allowFullScreen="true" flashvars="id=$3&mu=0&ap=0" quality="high" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer"> </embed>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:18;a:7:{s:2:"id";s:2:"19";s:5:"title";s:9:"justin.tv";s:7:"website";s:20:"http://www.justin.tv";s:10:"regexmatch";s:36:"http://www.justin.tv/([A-Z0-9]*)(.*)";s:9:"embedcode";s:494:"
<object type="application/x-shockwave-flash" height="300" width="400" id="live_embed_player_flash" data="http://www.justin.tv/widgets/live_embed_player.swf?channel=$1" bgcolor="#000000"><param name="allowFullScreen" value="true" /><param name="allowScriptAccess" value="always" /><param name="allowNetworking" value="all" /><param name="movie" value="http://www.justin.tv/widgets/live_embed_player.swf" /><param name="flashvars" value="channel=$1&auto_play=false&start_volume=25" /></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:19;a:7:{s:2:"id";s:2:"20";s:5:"title";s:10:"SchoolTube";s:7:"website";s:25:"http://www.schooltube.com";s:10:"regexmatch";s:48:"http://www.schooltube.com/video/([A-Z0-9]*)/(.*)";s:9:"embedcode";s:529:"
<object width="500" height="375"><param name="movie" value="http://www.schooltube.com/v/$1" /><param name="allowFullScreen" value="true" /><param name="allowscriptaccess" value="always" /><embed src="http://www.schooltube.com/v/16483926ba522476e7ae" type="application/x-shockwave-flash" allowFullScreen="true" allowscriptaccess="always" width="500" height="375" FlashVars="gig_lt=1281633293655&gig_pt=1281633309820&gig_g=2"></embed> <param name="FlashVars" value="gig_lt=1281633293655&gig_pt=1281633309820&gig_g=2" /></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:20;a:7:{s:2:"id";s:2:"21";s:5:"title";s:7:"MySpace";s:7:"website";s:22:"http://www.myspace.com";s:10:"regexmatch";s:83:"http://vids.myspace.com/index.cfm\?fuseaction=vids.individual\&amp;videoid=([0-9]*)";s:9:"embedcode";s:444:"
<object width="425px" height="360px" ><param name="allowFullScreen" value="true"/><param name="wmode" value="transparent"/><param name="movie" value="http://mediaservices.myspace.com/services/media/embed.aspx/m=$1,t=1,mt=video"/><embed src="http://mediaservices.myspace.com/services/media/embed.aspx/m=$1,t=1,mt=video" width="425" height="360" allowFullScreen="true" type="application/x-shockwave-flash" wmode="transparent"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:21;a:7:{s:2:"id";s:2:"22";s:5:"title";s:8:"Mefeedia";s:7:"website";s:23:"http://www.mefeedia.com";s:10:"regexmatch";s:38:"http://www.mefeedia.com/watch/([0-9]*)";s:9:"embedcode";s:121:"
<iframe scrolling="no" frameborder="0" width="640" height="450" src="http://www.mefeedia.com/watch/$1&iframe"></iframe>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:22;a:7:{s:2:"id";s:2:"24";s:5:"title";s:11:"DailyMotion";s:7:"website";s:26:"http://www.dailymotion.com";s:10:"regexmatch";s:49:"http://www.dailymotion.com/video/([A-Z0-9]*)_(.*)";s:9:"embedcode";s:436:"
<object width="480" height="360"><param name="movie" value="http://www.dailymotion.com/swf/video/$1?additionalInfos=0"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><embed type="application/x-shockwave-flash" src="http://www.dailymotion.com/swf/video/$1?additionalInfos=0" width="480" height="360" allowfullscreen="true" allowscriptaccess="always"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:23;a:7:{s:2:"id";s:2:"25";s:5:"title";s:11:"Clipfish.de";s:7:"website";s:22:"http://www.clipfish.de";s:10:"regexmatch";s:43:"http://www.clipfish.de/video/([0-9]*)/(.*)/";s:9:"embedcode";s:745:"
<object codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="464" height="384" > <param name="allowScriptAccess" value="always" /> <param name="movie" value="http://www.clipfish.de/cfng/flash/clipfish_player_3.swf?as=0&videoid=$1&r=1&area=e&c=990000" /> <param name="bgcolor" value="#ffffff" /> <param name="allowFullScreen" value="true" /> <embed src="http://www.clipfish.de/cfng/flash/clipfish_player_3.swf?as=0&vid=$1&r=1&area=e&c=990000" quality="high" bgcolor="#990000" width="464" height="384" name="player" align="middle" allowFullScreen="true" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:24;a:7:{s:2:"id";s:2:"26";s:5:"title";s:5:"Goear";s:7:"website";s:20:"http://www.goear.com";s:10:"regexmatch";s:44:"http://www.goear.com/listen/([A-Z0-9]*)/(.*)";s:9:"embedcode";s:211:"
<object width="353" height="132"><embed src="http://www.goear.com/files/external.swf?file=$1" type="application/x-shockwave-flash" wmode="transparent" quality="high" width="353" height="132"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:25;a:7:{s:2:"id";s:2:"27";s:5:"title";s:8:"Clipmoon";s:7:"website";s:23:"http://www.clipmoon.com";s:10:"regexmatch";s:49:"http://www.clipmoon.com/videos/([0-9]*)/(.*).html";s:9:"embedcode";s:363:"
<embed src="http://www.clipmoon.com/flvplayer.swf" FlashVars="config=http://www.clipmoon.com/flvplayer.php?viewkey=$1&external=no" quality="high" bgcolor="#000000" wmode="transparent" width="460" height="357" loop="false" align="middle" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"  scale="exactfit" > </embed>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:26;a:7:{s:2:"id";s:2:"28";s:5:"title";s:7:"Stagevu";s:7:"website";s:22:"http://www.stagevu.com";s:10:"regexmatch";s:36:"http://stagevu.com/video/([A-Z0-9]*)";s:9:"embedcode";s:185:"
<iframe style="overflow: hidden; border: 0; width: 720px; height: 362px" src="http://stagevu.com/embed?width=720&amp;height=306&amp;background=000&amp;uid=$1" scrolling="no"></iframe>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:27;a:7:{s:2:"id";s:2:"29";s:5:"title";s:7:"Mail.ru";s:7:"website";s:18:"http://www.mail.ru";s:10:"regexmatch";s:57:"http://video.mail.ru/mail/([0-9]*)/([0-9]*)/([0-9]*).html";s:9:"embedcode";s:353:"
<object width=626 height=367><param name="allowScriptAccess" value="always" /><param name="movie" value="http://img.mail.ru/r/video2/player_v2.swf?movieSrc=mail/$1/$2/$3" /><embed src=http://img.mail.ru/r/video2/player_v2.swf?movieSrc=mail/$1/$2/$3 type="application/x-shockwave-flash" width=626 height=367 allowScriptAccess="always"></embed></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:28;a:7:{s:2:"id";s:2:"30";s:5:"title";s:7:"Twitvid";s:7:"website";s:22:"http://www.twitvid.com";s:10:"regexmatch";s:34:"http://www.twitvid.com/([A-Z0-9]*)";s:9:"embedcode";s:434:"
<object width="425" height="344"><param name="movie" value="http://www.twitvid.com/player/$1"></param><param name="allowscriptaccess" value="always"></param><param name="allowFullScreen" value="true"></param><embed type="application/x-shockwave-flash" src="http://www.twitvid.com/player/$1" quality="high" allowscriptaccess="always" allowNetworking="all" allowfullscreen="true" wmode="transparent" height="344" width="425"></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:29;a:7:{s:2:"id";s:2:"31";s:5:"title";s:6:"Trtube";s:7:"website";s:21:"http://www.trtube.com";s:10:"regexmatch";s:40:"http://www.trtube.com/(.*)-([0-9]*).html";s:9:"embedcode";s:946:"
<object width="425" height="350"><param name="allowScriptAccess" value="always"><param name="movie" value="http://www.trtube.com/mediaplayer_3_15.swf?file=http://www.trtube.com/playlist.php?v=$2&image=http://resim.trtube.com/a/102/$2.gif&logo=http://load.trtube.com/img/logoembed.gif&linkfromdisplay=false&linktarget=_blank&autostart=false"><param name="quality" value="high"><param name="bgcolor" value="#ffffff"><param name="allowfullscreen" value="true"><embed src="http://www.trtube.com/mediaplayer_3_15.swf?file=http://www.trtube.com/playlist.php?v=$2&image=http://resim.trtube.com/a/102/$2.gif&logo=http://load.trtube.com/img/logoembed.gif&linkfromdisplay=false&linktarget=_blank&autostart=false" quality="high" bgcolor="#ffffff" allowfullscreen="true" width="450" height="370" name="player" align="middle" type="application/x-shockwave-flash" allowScriptAccess="always" pluginspage="http://www.macromedia.com/go/getflashplayer"></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:30;a:7:{s:2:"id";s:2:"33";s:5:"title";s:9:"MegaVideo";s:7:"website";s:24:"http://www.megavideo.com";s:10:"regexmatch";s:41:"http://(.*)megavideo.com/\?v=([A-Z_0-9]*)";s:9:"embedcode";s:305:"
<object width="640" height="344"><param name="movie" value="http://www.megavideo.com/v/$2.0.0"></param><param name="allowFullScreen" value="true"></param><embed src="http://www.megavideo.com/v/$2.0.0" type="application/x-shockwave-flash" allowfullscreen="true" width="640" height="344"></embed></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:31;a:7:{s:2:"id";s:2:"32";s:5:"title";s:6:"BlogTV";s:7:"website";s:21:"http://www.blogtv.com";s:10:"regexmatch";s:53:"http://www.blogtv.com/Shows/([0-9]*)/([A-Z_0-9]*)(.*)";s:9:"embedcode";s:136:"
<embed width="445" height="374" src="http://www.blogtv.com/vb/$2" type="application/x-shockwave-flash" allowFullScreen="true"></embed>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:32;a:7:{s:2:"id";s:2:"34";s:5:"title";s:3:"VH1";s:7:"website";s:18:"http://www.vh1.com";s:10:"regexmatch";s:54:"http://www.vh1.com/video/(.*)/([0-9]*)/(.*).jhtml(.*?)";s:9:"embedcode";s:313:"
<embed src="http://media.mtvnservices.com/mgid:uma:video:vh1.com:$2" width="512" height="319" wmode="transparent" type="application/x-shockwave-flash" flashVars="configParams=vid%3D$2%26uri%3Dmgid%3Auma%3Avideo%3Avh1.com%3A$2%26instance%3Dvh1" allowFullScreen="true" allowScriptAccess="always" base="."></embed>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:33;a:7:{s:2:"id";s:2:"35";s:5:"title";s:3:"BET";s:7:"website";s:18:"http://www.bet.com";s:10:"regexmatch";s:33:"http://www.bet.com/video/([0-9]*)";s:9:"embedcode";s:235:"
<embed src="http://media.mtvnservices.com/mgid:media:video:bet.com:$1" width="512" height="319" wmode="transparent" type="application/x-shockwave-flash" flashVars="" allowFullScreen="true" allowScriptAccess="always" base="."></embed>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:34;a:7:{s:2:"id";s:2:"36";s:5:"title";s:4:"Espn";s:7:"website";s:18:"http://espn.go.com";s:10:"regexmatch";s:42:"http://espn.go.com/video/clip\?id=([0-9]*)";s:9:"embedcode";s:483:"
<object width="384" height="216" type="application/x-shockwave-flash" id="ESPN_VIDEO" data="http://espn.go.com/videohub/player/embed.swf" allowScriptAccess="always" allowNetworking="all"><param name="movie" value="http://espn.go.com/videohub/player/embed.swf" /><param name="allowFullScreen" value="true"/><param name="wmode" value="opaque"/><param name="allowScriptAccess" value="always"/><param name="allowNetworking" value="all"/><param name="flashVars" value="id=$1"/></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:35;a:7:{s:2:"id";s:2:"37";s:5:"title";s:11:"CNN iReport";s:7:"website";s:22:"http://ireport.cnn.com";s:10:"regexmatch";s:40:"http://ireport.cnn.com/docs/DOC-([0-9]*)";s:9:"embedcode";s:722:"
<object width="400" height="300" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="ep"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://ireport.cnn.com/themes/custom/resources/cvplayer/ireport_embed.swf?player=embed&configPath=http://ireport.cnn.com&playlistId=$1&contentId=$1/0&" /><param name="bgcolor" value="#FFFFFF" /><embed src="http://ireport.cnn.com/themes/custom/resources/cvplayer/ireport_embed.swf?player=embed&configPath=http://ireport.cnn.com&playlistId=$1&contentId=$1/0&" type="application/x-shockwave-flash" bgcolor="#FFFFFF" allowfullscreen="true" allowscriptaccess="always" width="400" height="300"></embed></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:36;a:7:{s:2:"id";s:2:"38";s:5:"title";s:3:"PBS";s:7:"website";s:20:"http://video.pbs.org";s:10:"regexmatch";s:36:"http://video.pbs.org/video/([0-9]*)/";s:9:"embedcode";s:642:"
<object width = "512" height = "328" > <param name = "movie" value = "http://www-tc.pbs.org/video/media/swf/PBSPlayer.swf" > </param><param name="flashvars" value="video=$1&player=viral&chapter=1" /> <param name="allowFullScreen" value="true"></param > <param name = "allowscriptaccess" value = "always" > </param><param name="wmode" value="transparent"></param ><embed src="http://www-tc.pbs.org/video/media/swf/PBSPlayer.swf" flashvars="video=$1&player=viral&chapter=1" type="application/x-shockwave-flash" allowscriptaccess="always" wmode="transparent" allowfullscreen="true" width="512" height="328" bgcolor="#000000"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:37;a:7:{s:2:"id";s:2:"41";s:5:"title";s:9:"Stream.cz";s:7:"website";s:20:"http://www.stream.cz";s:10:"regexmatch";s:33:"http://(.*)stream.cz/([0-9]*)(.*)";s:9:"embedcode";s:428:"
<object height="382" width="624"><param name="movie" id="VideoSpot" value="http://www.stream.cz/object/$2$3"><param name="allowfullscreen" value="true"><param name="allowscriptaccess" value="always"><param name="wmode" value="transparent"><embed src="http://www.stream.cz/object/$2$3" type="application/x-shockwave-flash" wmode="transparent" allowfullscreen="true" allowscriptaccess="always" height="382" width="624"></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:38;a:7:{s:2:"id";s:2:"39";s:5:"title";s:3:"TNT";s:7:"website";s:17:"http://www.tnt.tv";s:10:"regexmatch";s:53:"http://www.tnt.tv/dramavision/index.jsp\?oid=([0-9]*)";s:9:"embedcode";s:580:"
<object width="442" height="375" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="ep"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://i.cdn.turner.com/v5cache/TNT/cvp/tnt_embed.swf?context=embed&videoId=$1" /><param name="bgcolor" "value="#FFFFFF" /><embed src="http://i.cdn.turner.com/v5cache/TNT/cvp/tnt_embed.swf?context=embed&videoId=$1" type="application/x-shockwave-flash" bgcolor="#FFFFFF" allowfullscreen="true" allowscriptaccess="always" width="442" height="375"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:39;a:7:{s:2:"id";s:2:"40";s:5:"title";s:14:"Comedy Central";s:7:"website";s:28:"http://www.comedycentral.com";s:10:"regexmatch";s:81:"http://www.comedycentral.com/videos/index.jhtml\?videoId=([0-9]*)\&amp;title=(.*)";s:9:"embedcode";s:305:"
<embed style="display:block" src="http://media.mtvnservices.com/mgid:cms:item:comedycentral.com:$1" width="360" height="301" type="application/x-shockwave-flash" wmode="window" allowFullscreen="true" flashvars="autoPlay=false" allowscriptaccess="always" allownetworking="all" bgcolor="#000000"></embed>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:40;a:7:{s:2:"id";s:2:"42";s:5:"title";s:14:"BlogDumpsVideo";s:7:"website";s:29:"http://www.blogdumpsvideo.com";s:10:"regexmatch";s:61:"http://www.blogdumpsvideo.com/action/viewvideo/([0-9]*)/(.*)/";s:9:"embedcode";s:472:"
<embed src="http://www.blogdumpsvideo.com/HDplayer.swf" FlashVars="config=http://www.blogdumpsvideo.com/videoConfigXmlCodeHD.php?pg=video_$1_no_0_extsite&playList=http://www.blogdumpsvideo.com/videoPlaylistXmlCodeHD.php?pg=video_$1" quality="high" bgcolor="#000000" width="600" height="350" name="flvplayer" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowFullScreen="true" />
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:41;a:7:{s:2:"id";s:2:"43";s:5:"title";s:7:"Reuters";s:7:"website";s:22:"http://www.reuters.com";s:10:"regexmatch";s:61:"http://www.reuters.com/news/video/story\?videoId=([0-9]*)(.*)";s:9:"embedcode";s:630:"
<object type="application/x-shockwave-flash" data="http://www.reuters.com/resources_v2/flash/video_embed.swf?videoId=$1" width="460" height="259"><param name="movie" value="http://www.reuters.com/resources_v2/flash/video_embed.swf?videoId=$1"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><param name="wmode" value="transparent"><embed src="http://www.reuters.com/resources_v2/flash/video_embed.swf?videoId=$1" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="460" height="259" wmode="transparent"></embed></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:42;a:7:{s:2:"id";s:2:"44";s:5:"title";s:15:"MarketNewsVideo";s:7:"website";s:26:"http://www.marketnewsvideo";s:10:"regexmatch";s:58:"http://www.marketnewsvideo.com/embed/\?id=([A-Z_0-9]*)(.*)";s:9:"embedcode";s:207:"
<iframe src="http://www.marketnewsvideo.com/?id=$1&mv=1&embed=1&width=400&height=320" frameborder="0" width="400" height="320" marginheight="0" marginwidth="0" scrolling="no" name="mnv1282073139"></iframe>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:43;a:7:{s:2:"id";s:2:"45";s:5:"title";s:13:"Clipsyndicate";s:7:"website";s:28:"http://www.clipsyndicate.com";s:10:"regexmatch";s:65:"http://www.clipsyndicate.com/video/playlist/([0-9]*)/([0-9]*)(.*)";s:9:"embedcode";s:707:"
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="cs_player" width="425" height="330"><param name="movie" value="http://eplayer.clipsyndicate.com/cs_api/get_swf/3/&amp;pl_id=$1&amp;page_count=5&amp;windows=1&amp;show_title=0&amp;va_id=$2&amp;rwpid=273&amp;auto_start=0&amp;auto_next=1" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><embed src="http://eplayer.clipsyndicate.com/cs_api/get_swf/3/&amp;pl_id=$1&amp;page_count=5&amp;windows=1&amp;show_title=0&amp;va_id=$2&amp;rwpid=273&amp;auto_start=0&amp;auto_next=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="330" /></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:44;a:7:{s:2:"id";s:2:"46";s:5:"title";s:7:"NyTimes";s:7:"website";s:24:"http://video.nytimes.com";s:10:"regexmatch";s:84:"http://video.nytimes.com/video/([0-9]*)/([0-9]*)/([0-9]*)/([A-Z_0-9]*)/([0-9]*)/(.*)";s:9:"embedcode";s:268:"
<iframe width="480" height="373" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" id="nyt_video_player" title="New York Times Video - Embed Player" src="http://graphics8.nytimes.com/bcvideo/1.0/iframe/embed.html?videoId=$5&playerType=embed"></iframe>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:45;a:7:{s:2:"id";s:2:"47";s:5:"title";s:9:"Clipshack";s:7:"website";s:24:"http://www.clipshack.com";s:10:"regexmatch";s:51:"http://www.clipshack.com/Clip.aspx\?key=([A-Z0-9]*)";s:9:"embedcode";s:111:"
<embed src="http://www.clipshack.com/player.swf?key=$1" width="430" height="370" wmode="transparent"></embed>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:46;a:7:{s:2:"id";s:2:"48";s:5:"title";s:5:"Mpora";s:7:"website";s:22:"http://video.mpora.com";s:10:"regexmatch";s:41:"http://video.mpora.com/watch/([A-Z0-9]*)/";s:9:"embedcode";s:311:"
<object id="mpora_$1" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="480" height="315"><param name="movie" value="http://video.mpora.com/p/$1" /><param name="allowfullscreen" value="true" /><embed src="http://video.mpora.com/p/$1" width="480" height="315" allowfullscreen="true"></embed></object>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:47;a:7:{s:2:"id";s:2:"49";s:5:"title";s:12:"Izlesene.com";s:7:"website";s:23:"http://www.izlesene.com";s:10:"regexmatch";s:43:"http://www.izlesene.com/video/(.*)/([0-9]*)";s:9:"embedcode";s:462:"
<object width="400" height="300"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://www.izlesene.com/embedplayer.swf?video=$2" /><embed src="http://www.izlesene.com/embedplayer.swf?video=$2" wmode="window" bgcolor="#000000" allowfullscreen="true" allowscriptaccess="always" menu="false" scale="noScale" width="400" height="300" type="application/x-shockwave-flash"></embed></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:48;a:7:{s:2:"id";s:2:"50";s:5:"title";s:10:"Rambler.ru";s:7:"website";s:21:"http://www.rambler.ru";s:10:"regexmatch";s:61:"http://vision.rambler.ru/users/([A-Z0-9]*)/([0-9]*)/([0-9]*)/";s:9:"embedcode";s:534:"
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="390" height="370"><param name="wmode" value="transparent"/><param name="allowFullScreen" value="true"/><param name="movie" value="http://vision.rambler.ru/i/e.swf?id=$1/$2/$3&logo=1" /><embed src="http://vision.rambler.ru/i/e.swf?id=$1/$2/$3&logo=1" width="390" height="370" type="application/x-shockwave-flash" wmode="transparent" allowFullScreen="true" /></object>

";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}i:49;a:7:{s:2:"id";s:2:"51";s:5:"title";s:10:"Tangle.com";s:7:"website";s:21:"http://www.tangle.com";s:10:"regexmatch";s:53:"http://www.tangle.com/view_video\?viewkey=([A-Z0-9]*)";s:9:"embedcode";s:305:"
<embed src="http://www.tangle.com/flash/swf/flvplayer.swf" FlashVars="viewkey=$1" wmode="transparent" quality="high" width="330" height="270" name="tangle" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" /></embed>
";s:6:"height";s:1:"0";s:5:"width";s:1:"0";}}';
?>