<?php
$mediaProCache = 'a:63:{i:0;a:7:{s:2:"id";s:1:"1";s:5:"title";s:7:"Youtube";s:7:"website";s:22:"http://www.youtube.com";s:10:"regexmatch";s:126:"htt(p|ps)://[\w.]+youtube\.[\w]+/watch[(\?|\?feature=player_embedded&amp;)\#!]+v=([\w-]+)[\w&;+=-]*[\#t=]*([\d]*)[&;10wshdq=]*";s:9:"embedcode";s:121:"<iframe width="480" height="600" src="//www.youtube.com/embed/$2?fs=1&start=$3" frameborder="0" allowfullscreen></iframe>";s:6:"height";s:3:"385";s:5:"width";s:3:"640";}i:1;a:7:{s:2:"id";s:1:"2";s:5:"title";s:8:"Metacafe";s:7:"website";s:23:"http://www.metacafe.com";s:10:"regexmatch";s:62:"http://www\.metacafe\.com/watch/([\w-]+/[\w_]*)[\w&;=\+_\-\/]*";s:9:"embedcode";s:220:"<embed src="http://www.metacafe.com/fplayer/$1.swf" width="480" height="600" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent"></embed>";s:6:"height";s:3:"334";s:5:"width";s:3:"540";}i:2;a:7:{s:2:"id";s:1:"3";s:5:"title";s:8:"Facebook";s:7:"website";s:23:"http://www.facebook.com";s:10:"regexmatch";s:62:"http://www\.facebook\.com/video/video\.php\?v=([\w]+)&*[\w;=]*";s:9:"embedcode";s:390:"<object width="480" height="600" >
       <param name="allowfullscreen" value="true" />
       <param name="allowscriptaccess" value="always" />
       <param name="movie" value="http://www.facebook.com/v/$1" />
       <embed src="http://www.facebook.com/v/$1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="480" height="600"></embed></object>";s:6:"height";s:3:"385";s:5:"width";s:3:"640";}i:3;a:7:{s:2:"id";s:1:"4";s:5:"title";s:5:"Vimeo";s:7:"website";s:20:"http://www.vimeo.com";s:10:"regexmatch";s:50:"htt(p|ps)://[w\.]*vimeo\.com/([\d]+)[\w&;=\?+%/-]*";s:9:"embedcode";s:149:"<iframe src="//player.vimeo.com/video/$2" width="480" height="600" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>";s:6:"height";s:3:"385";s:5:"width";s:3:"640";}i:4;a:7:{s:2:"id";s:1:"7";s:5:"title";s:4:"Veoh";s:7:"website";s:19:"http://www.veoh.com";s:10:"regexmatch";s:44:"http://www\.veoh\.com/(.*)/watch/([A-Z0-9]*)";s:9:"embedcode";s:727:"<object width="480" height="600" id="veohFlashPlayer" name="veohFlashPlayer"><param name="movie" value="http://www.veoh.com/static/swf/webplayer/WebPlayer.swf?version=AFrontend.5.5.2.1066&permalinkId=$2&player=videodetailsembedded&videoAutoPlay=0&id=anonymous"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.veoh.com/static/swf/webplayer/WebPlayer.swf?version=AFrontend.5.5.2.1066&permalinkId=$2&player=videodetailsembedded&videoAutoPlay=0&id=anonymous" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="480" height="600" id="veohFlashPlayerEmbed" name="veohFlashPlayerEmbed"></embed></object>";s:6:"height";s:3:"341";s:5:"width";s:3:"410";}i:5;a:7:{s:2:"id";s:1:"8";s:5:"title";s:5:"Youku";s:7:"website";s:20:"http://www.youku.com";s:10:"regexmatch";s:55:"http://([A-Z0-9]*).youku.com/v_show/id_([A-Z0-9]*).html";s:9:"embedcode";s:193:"
<embed src="http://player.youku.com/player.php/sid/$2/v.swf" quality="high" width="480" height="600" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash"></embed>";s:6:"height";s:3:"400";s:5:"width";s:3:"480";}i:6;a:7:{s:2:"id";s:2:"10";s:5:"title";s:6:"Rutube";s:7:"website";s:16:"http://rutube.ru";s:10:"regexmatch";s:55:"http://rutube.ru/tracks/([A-Z0-9]*).html\?v=([A-Z0-9]*)";s:9:"embedcode";s:348:"
<OBJECT width="480" height="600"><PARAM name="movie" value="http://video.rutube.ru/$2"></PARAM><PARAM name="wmode" value="window"></PARAM><PARAM name="allowFullScreen" value="true"></PARAM><EMBED src="http://video.rutube.ru/$2" type="application/x-shockwave-flash" wmode="window" width="480" height="600" allowFullScreen="true" ></EMBED></OBJECT>
";s:6:"height";s:3:"353";s:5:"width";s:3:"470";}i:7;a:7:{s:2:"id";s:2:"13";s:5:"title";s:8:"LiveLeak";s:7:"website";s:23:"http://www.liveleak.com";s:10:"regexmatch";s:45:"htt(p|ps)://www.liveleak.com/view\?i=([^<>]+)";s:9:"embedcode";s:374:"
<object width="480" height="600"><param name="movie" value="htt$1://www.liveleak.com/e/$2"></param><param name="wmode" value="transparent"></param><param name="allowscriptaccess" value="always"></param><embed src="htt$1://www.liveleak.com/e/$2" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" width="480" height="600"></embed></object>

";s:6:"height";s:3:"370";s:5:"width";s:3:"450";}i:8;a:7:{s:2:"id";s:2:"16";s:5:"title";s:14:"Funnyordie.com";s:7:"website";s:25:"http://www.funnyordie.com";s:10:"regexmatch";s:53:"http://www.funnyordie.com/videos/([A-Z0-9]*)/([^<>]+)";s:9:"embedcode";s:584:"
<object width="480" height="600" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="ordie_player_$1"><param name="movie" value="http://player.ordienetworks.com/flash/fodplayer.swf" /><param name="flashvars" value="key=$1" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always"></param><embed width="480" height="600" flashvars="key=$1" allowfullscreen="true" allowscriptaccess="always" quality="high" src="http://player.ordienetworks.com/flash/fodplayer.swf" name="ordie_player_$1" type="application/x-shockwave-flash"></embed></object>

";s:6:"height";s:3:"400";s:5:"width";s:3:"480";}i:9;a:7:{s:2:"id";s:2:"18";s:5:"title";s:7:"Crackle";s:7:"website";s:22:"http://www.crackle.com";s:10:"regexmatch";s:43:"http://www.crackle.com/c/(.*)/(.*)/([0-9]*)";s:9:"embedcode";s:358:"
<embed src="http://www.crackle.com/p/$1/$2.swf" quality="high" bgcolor="#869ca7" width="480" height="600" name="mtgPlayer" align="middle" play="true" loop="false" allowFullScreen="true" flashvars="id=$3&mu=0&ap=0" quality="high" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer"> </embed>

";s:6:"height";s:3:"281";s:5:"width";s:3:"500";}i:10;a:7:{s:2:"id";s:2:"20";s:5:"title";s:10:"SchoolTube";s:7:"website";s:25:"http://www.schooltube.com";s:10:"regexmatch";s:52:"http://www.schooltube.com/video/([A-Z0-9]*)/([^<>]+)";s:9:"embedcode";s:529:"
<object width="480" height="600"><param name="movie" value="http://www.schooltube.com/v/$1" /><param name="allowFullScreen" value="true" /><param name="allowscriptaccess" value="always" /><embed src="http://www.schooltube.com/v/16483926ba522476e7ae" type="application/x-shockwave-flash" allowFullScreen="true" allowscriptaccess="always" width="480" height="600" FlashVars="gig_lt=1281633293655&gig_pt=1281633309820&gig_g=2"></embed> <param name="FlashVars" value="gig_lt=1281633293655&gig_pt=1281633309820&gig_g=2" /></object>

";s:6:"height";s:3:"375";s:5:"width";s:3:"500";}i:11;a:7:{s:2:"id";s:2:"21";s:5:"title";s:7:"MySpace";s:7:"website";s:22:"http://www.myspace.com";s:10:"regexmatch";s:83:"http://vids.myspace.com/index.cfm\?fuseaction=vids.individual\&amp;videoid=([0-9]*)";s:9:"embedcode";s:439:"
<object width="480" height="600"><param name="allowFullScreen" value="true"/><param name="wmode" value="transparent"/><param name="movie" value="http://mediaservices.myspace.com/services/media/embed.aspx/m=$1,t=1,mt=video"/><embed src="http://mediaservices.myspace.com/services/media/embed.aspx/m=$1,t=1,mt=video" width="480" height="600" allowFullScreen="true" type="application/x-shockwave-flash" wmode="transparent"></embed></object>

";s:6:"height";s:3:"360";s:5:"width";s:3:"425";}i:12;a:7:{s:2:"id";s:2:"22";s:5:"title";s:8:"Mefeedia";s:7:"website";s:23:"http://www.mefeedia.com";s:10:"regexmatch";s:38:"http://www.mefeedia.com/watch/([0-9]*)";s:9:"embedcode";s:121:"
<iframe scrolling="no" frameborder="0" width="480" height="600" src="http://www.mefeedia.com/watch/$1&iframe"></iframe>
";s:6:"height";s:3:"450";s:5:"width";s:3:"640";}i:13;a:7:{s:2:"id";s:2:"24";s:5:"title";s:11:"DailyMotion";s:7:"website";s:26:"http://www.dailymotion.com";s:10:"regexmatch";s:153:"htt(p|ps)://www.dailymotion.com/video/([A-Z0-9]*)_([^<>]+)ZSPLITMZhtt(p|ps)://www.dailymotion.com/video/([A-Z0-9]*)ZSPLITMZhtt(p|ps)://dai.ly/([A-Z0-9]*)";s:9:"embedcode";s:119:"
<iframe frameborder="0" width="480" height="600" src="//www.dailymotion.com/embed/video/$2" allowfullscreen></iframe>
";s:6:"height";s:3:"360";s:5:"width";s:3:"480";}i:14;a:7:{s:2:"id";s:2:"27";s:5:"title";s:8:"Clipmoon";s:7:"website";s:23:"http://www.clipmoon.com";s:10:"regexmatch";s:49:"http://www.clipmoon.com/videos/([0-9]*)/(.*).html";s:9:"embedcode";s:363:"
<embed src="http://www.clipmoon.com/flvplayer.swf" FlashVars="config=http://www.clipmoon.com/flvplayer.php?viewkey=$1&external=no" quality="high" bgcolor="#000000" wmode="transparent" width="480" height="600" loop="false" align="middle" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"  scale="exactfit" > </embed>

";s:6:"height";s:3:"357";s:5:"width";s:3:"460";}i:15;a:7:{s:2:"id";s:2:"29";s:5:"title";s:7:"Mail.ru";s:7:"website";s:18:"http://www.mail.ru";s:10:"regexmatch";s:57:"http://video.mail.ru/mail/([0-9]*)/([0-9]*)/([0-9]*).html";s:9:"embedcode";s:361:"
<object width="480" height="600"><param name="allowScriptAccess" value="always" /><param name="movie" value="http://img.mail.ru/r/video2/player_v2.swf?movieSrc=mail/$1/$2/$3" /><embed src=http://img.mail.ru/r/video2/player_v2.swf?movieSrc=mail/$1/$2/$3 type="application/x-shockwave-flash" width="480" height="600" allowScriptAccess="always"></embed></object>
";s:6:"height";s:3:"367";s:5:"width";s:3:"626";}i:16;a:7:{s:2:"id";s:2:"31";s:5:"title";s:6:"Trtube";s:7:"website";s:21:"http://www.trtube.com";s:10:"regexmatch";s:40:"http://www.trtube.com/(.*)-([0-9]*).html";s:9:"embedcode";s:946:"
<object width="480" height="600"><param name="allowScriptAccess" value="always"><param name="movie" value="http://www.trtube.com/mediaplayer_3_15.swf?file=http://www.trtube.com/playlist.php?v=$2&image=http://resim.trtube.com/a/102/$2.gif&logo=http://load.trtube.com/img/logoembed.gif&linkfromdisplay=false&linktarget=_blank&autostart=false"><param name="quality" value="high"><param name="bgcolor" value="#ffffff"><param name="allowfullscreen" value="true"><embed src="http://www.trtube.com/mediaplayer_3_15.swf?file=http://www.trtube.com/playlist.php?v=$2&image=http://resim.trtube.com/a/102/$2.gif&logo=http://load.trtube.com/img/logoembed.gif&linkfromdisplay=false&linktarget=_blank&autostart=false" quality="high" bgcolor="#ffffff" allowfullscreen="true" width="480" height="600" name="player" align="middle" type="application/x-shockwave-flash" allowScriptAccess="always" pluginspage="http://www.macromedia.com/go/getflashplayer"></object>
";s:6:"height";s:3:"350";s:5:"width";s:3:"425";}i:17;a:7:{s:2:"id";s:2:"34";s:5:"title";s:3:"VH1";s:7:"website";s:18:"http://www.vh1.com";s:10:"regexmatch";s:54:"http://www.vh1.com/video/(.*)/([0-9]*)/(.*).jhtml(.*?)";s:9:"embedcode";s:313:"
<embed src="http://media.mtvnservices.com/mgid:uma:video:vh1.com:$2" width="480" height="600" wmode="transparent" type="application/x-shockwave-flash" flashVars="configParams=vid%3D$2%26uri%3Dmgid%3Auma%3Avideo%3Avh1.com%3A$2%26instance%3Dvh1" allowFullScreen="true" allowScriptAccess="always" base="."></embed>
";s:6:"height";s:3:"319";s:5:"width";s:3:"512";}i:18;a:7:{s:2:"id";s:2:"35";s:5:"title";s:3:"BET";s:7:"website";s:18:"http://www.bet.com";s:10:"regexmatch";s:33:"http://www.bet.com/video/([0-9]*)";s:9:"embedcode";s:235:"
<embed src="http://media.mtvnservices.com/mgid:media:video:bet.com:$1" width="480" height="600" wmode="transparent" type="application/x-shockwave-flash" flashVars="" allowFullScreen="true" allowScriptAccess="always" base="."></embed>
";s:6:"height";s:3:"319";s:5:"width";s:3:"512";}i:19;a:7:{s:2:"id";s:2:"36";s:5:"title";s:4:"Espn";s:7:"website";s:18:"http://espn.go.com";s:10:"regexmatch";s:42:"http://espn.go.com/video/clip\?id=([0-9]*)";s:9:"embedcode";s:483:"
<object width="480" height="600" type="application/x-shockwave-flash" id="ESPN_VIDEO" data="http://espn.go.com/videohub/player/embed.swf" allowScriptAccess="always" allowNetworking="all"><param name="movie" value="http://espn.go.com/videohub/player/embed.swf" /><param name="allowFullScreen" value="true"/><param name="wmode" value="opaque"/><param name="allowScriptAccess" value="always"/><param name="allowNetworking" value="all"/><param name="flashVars" value="id=$1"/></object>
";s:6:"height";s:3:"216";s:5:"width";s:3:"384";}i:20;a:7:{s:2:"id";s:2:"38";s:5:"title";s:3:"PBS";s:7:"website";s:20:"http://video.pbs.org";s:10:"regexmatch";s:36:"http://video.pbs.org/video/([0-9]*)/";s:9:"embedcode";s:636:"
<object width="480" height="600" > <param name="movie" value = "http://www-tc.pbs.org/video/media/swf/PBSPlayer.swf" > </param><param name="flashvars" value="video=$1&player=viral&chapter=1" /> <param name="allowFullScreen" value="true"></param > <param name = "allowscriptaccess" value = "always" > </param><param name="wmode" value="transparent"></param ><embed src="http://www-tc.pbs.org/video/media/swf/PBSPlayer.swf" flashvars="video=$1&player=viral&chapter=1" type="application/x-shockwave-flash" allowscriptaccess="always" wmode="transparent" allowfullscreen="true" width="480" height="600" bgcolor="#000000"></embed></object>

";s:6:"height";s:3:"328";s:5:"width";s:3:"512";}i:21;a:7:{s:2:"id";s:2:"39";s:5:"title";s:3:"TNT";s:7:"website";s:17:"http://www.tnt.tv";s:10:"regexmatch";s:53:"http://www.tnt.tv/dramavision/index.jsp\?oid=([0-9]*)";s:9:"embedcode";s:581:"
<object width="480" height="600"" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="ep"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://i.cdn.turner.com/v5cache/TNT/cvp/tnt_embed.swf?context=embed&videoId=$1" /><param name="bgcolor" "value="#FFFFFF" /><embed src="http://i.cdn.turner.com/v5cache/TNT/cvp/tnt_embed.swf?context=embed&videoId=$1" type="application/x-shockwave-flash" bgcolor="#FFFFFF" allowfullscreen="true" allowscriptaccess="always" width="480" height="600"></embed></object>

";s:6:"height";s:3:"375";s:5:"width";s:3:"442";}i:22;a:7:{s:2:"id";s:2:"40";s:5:"title";s:14:"Comedy Central";s:7:"website";s:28:"http://www.comedycentral.com";s:10:"regexmatch";s:81:"http://www.comedycentral.com/videos/index.jhtml\?videoId=([0-9]*)\&amp;title=(.*)";s:9:"embedcode";s:305:"
<embed style="display:block" src="http://media.mtvnservices.com/mgid:cms:item:comedycentral.com:$1" width="360" height="301" type="application/x-shockwave-flash" wmode="window" allowFullscreen="true" flashvars="autoPlay=false" allowscriptaccess="always" allownetworking="all" bgcolor="#000000"></embed>

";s:6:"height";s:3:"301";s:5:"width";s:3:"360";}i:23;a:7:{s:2:"id";s:2:"43";s:5:"title";s:7:"Reuters";s:7:"website";s:22:"http://www.reuters.com";s:10:"regexmatch";s:65:"http://www.reuters.com/news/video/story\?videoId=([0-9]*)([^<>]+)";s:9:"embedcode";s:630:"
<object type="application/x-shockwave-flash" data="http://www.reuters.com/resources_v2/flash/video_embed.swf?videoId=$1" width="480" height="600"><param name="movie" value="http://www.reuters.com/resources_v2/flash/video_embed.swf?videoId=$1"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><param name="wmode" value="transparent"><embed src="http://www.reuters.com/resources_v2/flash/video_embed.swf?videoId=$1" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="480" height="600" wmode="transparent"></embed></object>
";s:6:"height";s:3:"259";s:5:"width";s:3:"460";}i:24;a:7:{s:2:"id";s:2:"44";s:5:"title";s:15:"MarketNewsVideo";s:7:"website";s:30:"http://www.marketnewsvideo.com";s:10:"regexmatch";s:62:"http://www.marketnewsvideo.com/embed/\?id=([A-Z_0-9]*)([^<>]+)";s:9:"embedcode";s:207:"
<iframe src="http://www.marketnewsvideo.com/?id=$1&mv=1&embed=1&width=400&height=320" frameborder="0" width="480" height="600" marginheight="0" marginwidth="0" scrolling="no" name="mnv1282073139"></iframe>
";s:6:"height";s:3:"320";s:5:"width";s:3:"400";}i:25;a:7:{s:2:"id";s:2:"45";s:5:"title";s:23:"Clipsyndicate PlayLists";s:7:"website";s:28:"http://www.clipsyndicate.com";s:10:"regexmatch";s:69:"http://www.clipsyndicate.com/video/playlist/([0-9]*)/([0-9]*)([^<>]+)";s:9:"embedcode";s:707:"
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="cs_player" width="480" height="600"><param name="movie" value="http://eplayer.clipsyndicate.com/cs_api/get_swf/3/&amp;pl_id=$1&amp;page_count=5&amp;windows=1&amp;show_title=0&amp;va_id=$2&amp;rwpid=273&amp;auto_start=0&amp;auto_next=1" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><embed src="http://eplayer.clipsyndicate.com/cs_api/get_swf/3/&amp;pl_id=$1&amp;page_count=5&amp;windows=1&amp;show_title=0&amp;va_id=$2&amp;rwpid=273&amp;auto_start=0&amp;auto_next=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="480" height="600" /></object>
";s:6:"height";s:3:"330";s:5:"width";s:3:"425";}i:26;a:7:{s:2:"id";s:2:"46";s:5:"title";s:7:"NyTimes";s:7:"website";s:24:"http://video.nytimes.com";s:10:"regexmatch";s:88:"http://video.nytimes.com/video/([0-9]*)/([0-9]*)/([0-9]*)/([A-Z_0-9]*)/([0-9]*)/([^<>]+)";s:9:"embedcode";s:268:"
<iframe width="480" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" id="nyt_video_player" title="New York Times Video - Embed Player" src="http://graphics8.nytimes.com/bcvideo/1.0/iframe/embed.html?videoId=$5&playerType=embed"></iframe>

";s:6:"height";s:3:"373";s:5:"width";s:3:"480";}i:27;a:7:{s:2:"id";s:2:"49";s:5:"title";s:12:"Izlesene.com";s:7:"website";s:23:"http://www.izlesene.com";s:10:"regexmatch";s:43:"http://www.izlesene.com/video/(.*)/([0-9]*)";s:9:"embedcode";s:461:"
<object width="480" height="600"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://www.izlesene.com/embedplayer.swf?video=$2" /><embed src="http://www.izlesene.com/embedplayer.swf?video=$2" wmode="window" bgcolor="#000000" allowfullscreen="true" allowscriptaccess="always" menu="false" scale="noScale" width="480" height="600" type="application/x-shockwave-flash"></embed></object>
";s:6:"height";s:3:"300";s:5:"width";s:3:"400";}i:28;a:7:{s:2:"id";s:2:"50";s:5:"title";s:10:"Rambler.ru";s:7:"website";s:21:"http://www.rambler.ru";s:10:"regexmatch";s:61:"http://vision.rambler.ru/users/([A-Z0-9]*)/([0-9]*)/([0-9]*)/";s:9:"embedcode";s:533:"
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="480" height="600"><param name="wmode" value="transparent"/><param name="allowFullScreen" value="true"/><param name="movie" value="http://vision.rambler.ru/i/e.swf?id=$1/$2/$3&logo=1" /><embed src="http://vision.rambler.ru/i/e.swf?id=$1/$2/$3&logo=1" width="480" height="600" type="application/x-shockwave-flash" wmode="transparent" allowFullScreen="true" /></object>
";s:6:"height";s:3:"370";s:5:"width";s:3:"390";}i:29;a:7:{s:2:"id";s:2:"53";s:5:"title";s:5:"Yahoo";s:7:"website";s:22:"http://video.yahoo.com";s:10:"regexmatch";s:46:"http://video.yahoo.com/watch/([0-9]*)/([0-9]*)";s:9:"embedcode";s:769:"
 <object width="480" height="600""><param name="movie" value="http://d.yimg.com/static.video.yahoo.com/yep/YV_YEP.swf?ver=2.2.46" /><param name="allowFullScreen" value="true" /><param name="AllowScriptAccess" VALUE="always" /><param name="bgcolor" value="#000000" /><param name="flashVars" value="id=$2&vid=$1&lang=en-us&intl=us&thumbUrl=http%3A//l.yimg.com/a/i/us/sch/cn/video05/$1_rnd3230d645_19.jpg&embed=1" /><embed src="http://d.yimg.com/static.video.yahoo.com/yep/YV_YEP.swf?ver=2.2.46" type="application/x-shockwave-flash" width="480" height="600" allowFullScreen="true" AllowScriptAccess="always" bgcolor="#000000" flashVars="id=$2&vid=$1&lang=en-us&intl=us&thumbUrl=http%3A//l.yimg.com/a/i/us/sch/cn/video05/$1_rnd3230d645_19.jpg&embed=1" ></embed></object>

";s:6:"height";s:3:"322";s:5:"width";s:3:"512";}i:30;a:7:{s:2:"id";s:2:"56";s:5:"title";s:19:"Worldstarhiphop.com";s:7:"website";s:30:"http://www.worldstarhiphop.com";s:10:"regexmatch";s:62:"http://www.worldstarhiphop.com/videos/video.php\?v=([A-Z0-9]*)";s:9:"embedcode";s:333:"
<object width="480" height="600"><param name="movie" value="http://www.worldstarhiphop.com/videos/e/16711680/$1"><param name="allowFullScreen" value="true"></param><embed src="http://www.worldstarhiphop.com/videos/e/16711680/$1" type="application/x-shockwave-flash" allowFullscreen="true" width="480" height="600"></embed></object>
";s:6:"height";s:3:"374";s:5:"width";s:3:"448";}i:31;a:7:{s:2:"id";s:2:"58";s:5:"title";s:6:"JibJab";s:7:"website";s:21:"http://www.jibjab.com";s:10:"regexmatch";s:41:"http://www.jibjab.com/view/([A-Za-z0-9]*)";s:9:"embedcode";s:770:"
<object id="A64060" quality="high" data="http://static.jibjabcdn.com/sendables/aa7bc606/client/zero/ClientZero_EmbedViewer.swf?external_make_id=$1" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" width="480" height="600"><param name="wmode" value="transparent"></param><param name="movie" value="http://aka.zero.jibjab.com/client/zero/ClientZero_EmbedViewer.swf?external_make_id=$1"></param><param name="scaleMode" value="showAll"></param><param name="quality" value="high"></param><param name="allowNetworking" value="all"></param><param name="allowFullScreen" value="true" /><param name="FlashVars" value="external_make_id=$1"></param><param name="allowScriptAccess" value="always"></param></object>
";s:6:"height";s:3:"319";s:5:"width";s:3:"425";}i:32;a:7:{s:2:"id";s:2:"60";s:5:"title";s:3:"IGN";s:7:"website";s:18:"http://www.ign.com";s:10:"regexmatch";s:73:"http://www.ign.com/videos/([0-9]*)/([0-9]*)/([0-9]*)/([a-zA-Z0-9_=\-\?]*)";s:9:"embedcode";s:438:"
<object id="vid" class="ign-videoplayer" width="480" height="600" data="http://media.ign.com/ev/prod/embed.swf" type="application/x-shockwave-flash"><param name="movie" value="http://media.ign.com/ev/prod/embed.swf" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="bgcolor" value="#000000" /><param name="flashvars" value="url=http://www.ign.com/videos/$1/$2/$3/$4"/></object>
";s:6:"height";s:3:"270";s:5:"width";s:3:"480";}i:33;a:7:{s:2:"id";s:2:"61";s:5:"title";s:7:"Joystiq";s:7:"website";s:22:"http://www.joystiq.com";s:10:"regexmatch";s:43:"http://www.joystiq.com/video/([a-zA-Z0-9]*)";s:9:"embedcode";s:508:"
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="480" height="600" id="viddler"><param name="movie" value="http://www.viddler.com/simple/$1" /><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="true" /><param name="flashvars" value="fake=1"/><embed src="http://www.viddler.com/simple/$1" width="480" height="600" type="application/x-shockwave-flash" allowScriptAccess="always" allowFullScreen="true" flashvars="fake=1" name="viddler" ></embed></object>
";s:6:"height";s:3:"266";s:5:"width";s:3:"437";}i:34;a:7:{s:2:"id";s:2:"70";s:5:"title";s:11:"Google Maps";s:7:"website";s:23:"http://maps.google.com/";s:10:"regexmatch";s:47:"htt(p|ps)://(maps\.google\.[^">]+/\w*?\?[^">]+)";s:9:"embedcode";s:140:"
<iframe width="480" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="htt$1://$2&output=svembed"></iframe>
";s:6:"height";s:3:"350";s:5:"width";s:3:"425";}i:35;a:7:{s:2:"id";s:2:"71";s:5:"title";s:17:"Youtube Short Url";s:7:"website";s:22:"http://www.youtube.com";s:10:"regexmatch";s:48:"htt(p|ps)://[w\.]*youtu\.be/([-a-zA-Z0-9&;+=_]*)";s:9:"embedcode";s:142:"<iframe title="YouTube video player" width="480" height="600" src="//www.youtube.com/embed/$2?rel=0" frameborder="0" allowfullscreen></iframe>";s:6:"height";s:3:"385";s:5:"width";s:3:"640";}i:36;a:7:{s:2:"id";s:2:"82";s:5:"title";s:8:"own3d.tv";s:7:"website";s:19:"http://www.own3d.tv";s:10:"regexmatch";s:43:"http://www.own3d.tv/video/([0-9]*)/([^<>]+)";s:9:"embedcode";s:449:"
<object width="480" height="600">
    <param name="movie" value="http://www.own3d.tv/stream/$1" />
    <param name="allowscriptaccess" value="always" />
    <param name="allowfullscreen" value="true" />
    <param name="wmode" value="transparent" />
    <embed src="http://www.own3d.tv/stream/$1" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="640" height="360" wmode="transparent"></embed>
</object>
";s:6:"height";s:3:"360";s:5:"width";s:3:"640";}i:37;a:7:{s:2:"id";s:2:"83";s:5:"title";s:14:"Facebook Video";s:7:"website";s:23:"http://www.facebook.com";s:10:"regexmatch";s:69:"htt(p|ps)://www\.facebook\.com/video/embed\?video_id=([\w]+)&*[\w;=]*";s:9:"embedcode";s:529:"
<strong><div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document,"script", "facebook-jssdk"));</script>
<div class="fb-post" data-href="https://www.facebook.com/photo.php?v=$2" data-width="550"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/photo.php?v=$2">Post</a>
</div></div>
</strong>";s:6:"height";s:3:"385";s:5:"width";s:3:"640";}i:38;a:7:{s:2:"id";s:2:"84";s:5:"title";s:17:"Facebook Pictures";s:7:"website";s:23:"http://www.facebook.com";s:10:"regexmatch";s:60:"htt(p|ps)://www\.facebook\.com/photo.php\?v=([\w]+)&*[\w;=]*";s:9:"embedcode";s:529:"
<strong><div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document,"script", "facebook-jssdk"));</script>
<div class="fb-post" data-href="https://www.facebook.com/photo.php?v=$2" data-width="550"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/photo.php?v=$2">Post</a>
</div></div>
</strong>";s:6:"height";s:3:"385";s:5:"width";s:3:"640";}i:39;a:7:{s:2:"id";s:2:"87";s:5:"title";s:10:"SoundCloud";s:7:"website";s:25:"http://www.soundcloud.com";s:10:"regexmatch";s:90:"htt(p|ps)://w.soundcloud.com/player/\?url=https://api.soundcloud.com/tracks/([A-Za-z0-9]*)";s:9:"embedcode";s:157:"<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/$2"></iframe>";s:6:"height";s:3:"600";s:5:"width";s:3:"600";}i:40;a:7:{s:2:"id";s:2:"90";s:5:"title";s:20:"Facebook Video (New)";s:7:"website";s:23:"http://www.facebook.com";s:10:"regexmatch";s:50:"htt(p|ps)://www.facebook.com/video.php\?v=([0-9]*)";s:9:"embedcode";s:511:"
<div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document,"script", "facebook-jssdk"));</script>
<div class="fb-post" data-href="https://www.facebook.com/video.php?v=$2" data-width="466"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/view.php?v=$2">Post</a>
</div></div>
";s:6:"height";s:3:"385";s:5:"width";s:3:"466";}i:41;a:7:{s:2:"id";s:2:"91";s:5:"title";s:8:"coub.com";s:7:"website";s:15:"http://coub.com";s:10:"regexmatch";s:40:"htt(p|ps)://coub.com/view/([A-Za-z0-9]*)";s:9:"embedcode";s:194:"<iframe src="http://coub.com/embed/$2?muted=false&autostart=false&originalSize=false&hideTopBar=false&startWithHD=false" allowfullscreen="true" frameborder="0" width="480" height="600"></iframe>";s:6:"height";s:3:"367";s:5:"width";s:3:"480";}i:42;a:7:{s:2:"id";s:2:"92";s:5:"title";s:9:"Twitch.tv";s:7:"website";s:16:"http://twitch.tv";s:10:"regexmatch";s:59:"http://www.twitch.tv/([A-Za-z0-9]*)/([A-Za-z0-9]*)/([0-9]*)";s:9:"embedcode";s:495:"<object bgcolor="#000000" data="http://www.twitch.tv/swflibs/TwitchPlayer.swf" height="600" id="clip_embed_player_flash" type="application/x-shockwave-flash" width="480"><param name="movie" value="http://www.twitch.tv/swflibs/TwitchPlayer.swf" /><param name="allowScriptAccess" value="always" /><param name="allowNetworking" value="all" /><param name="allowFullScreen" value="true" /><param name="flashvars" value="channel=$1&amp;auto_play=false&amp;start_volume=25&amp;videoId=$2$3" /></object>";s:6:"height";s:3:"378";s:5:"width";s:3:"620";}i:43;a:7:{s:2:"id";s:2:"93";s:5:"title";s:10:"Deezer.com";s:7:"website";s:17:"http://Deezer.com";s:10:"regexmatch";s:45:"http://www.deezer.com/([A-Za-z0-9]*)/([0-9]*)";s:9:"embedcode";s:240:"<iframe scrolling="no" frameborder="0" allowTransparency="true" src="http://www.deezer.com/plugins/player?autoplay=false&playlist=true&width=700&height=240&cover=true&type=$1&id=$2&title=&app_id=undefined" width="480" height="600"></iframe>";s:6:"height";s:3:"240";s:5:"width";s:3:"700";}i:44;a:7:{s:2:"id";s:2:"94";s:5:"title";s:7:"buto.tv";s:7:"website";s:14:"http://buto.tv";s:10:"regexmatch";s:34:"http://play.buto.tv/([A-Za-z0-9]*)";s:9:"embedcode";s:145:"<iframe id="buto_iframe_Vmxtx" src="//embed.buto.tv/$1" width="480" height="600" frameborder="no" scrolling="no" allowfullscreen="true"></iframe>";s:6:"height";s:3:"360";s:5:"width";s:3:"640";}i:45;a:7:{s:2:"id";s:2:"95";s:5:"title";s:23:"Facebook Video (New v4)";s:7:"website";s:23:"http://www.facebook.com";s:10:"regexmatch";s:58:"htt(p|ps)://www.facebook.com/([0-9]*)/videos/([0-9]*)/(.*)";s:9:"embedcode";s:607:"
<div id="fb-root"></div><script>(function(d, s, id) {  var js, fjs = d.getElementsByTagName(s)[0];  if (d.getElementById(id)) return;  js = d.createElement(s); js.id = id;  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";  fjs.parentNode.insertBefore(js, fjs);}(document, "script", "facebook-jssdk"));</script><div class="fb-video" data-allowfullscreen="1" data-width="480" data-href="/$2/videos/vb.$2/$3/?type=1"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/$2/videos/$3/"><a href="https://www.facebook.com/$2/videos/$3/"></a></blockquote></div></div>
";s:6:"height";s:3:"385";s:5:"width";s:3:"466";}i:46;a:7:{s:2:"id";s:2:"96";s:5:"title";s:16:"Local/Remote Ogg";s:7:"website";s:0:"";s:10:"regexmatch";s:25:"htt(p|ps)://([^<>]+)\.ogg";s:9:"embedcode";s:362:"
<video height="600" width="480" controls>
  <source src="htt$1://$2.ogg" type="video/ogg">
  <object data="htt$1://$2.ogg" height="600" width="480">
    <PARAM NAME="src" VALUE="htt$1://$2.ogg">
    <PARAM NAME="AutoPlay" VALUE="true" >
    <PARAM NAME="Controller" VALUE="false" >
    <embed src="htt$1://$2.ogg" height="600" width="480">
  </object>
</video>
";s:6:"height";s:3:"350";s:5:"width";s:3:"425";}i:47;a:7:{s:2:"id";s:2:"98";s:5:"title";s:9:"Instagram";s:7:"website";s:20:"http://instagram.com";s:10:"regexmatch";s:63:"htt(p|ps)://[www\.]*instagram.com/p/([A-Za-z0-9\-\_]*)/([^<>]+)";s:9:"embedcode";s:1583:"<div><blockquote class="instagram-media" data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://instagram.com/p/$2/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_top"> </a></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script></div>
";s:6:"height";s:3:"360";s:5:"width";s:3:"640";}i:48;a:7:{s:2:"id";s:2:"99";s:5:"title";s:23:"Facebook Video (New v5)";s:7:"website";s:23:"http://www.facebook.com";s:10:"regexmatch";s:96:"(http|https):\/\/(|(.+?).)facebook.com/([\w\.\_]+/videos/|video.php\?v=)(\d+)(|((/|\?|\&)(.+?)))";s:9:"embedcode";s:642:"
<div id="fb-root"></div><script>(function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12";fjs.parentNode.insertBefore(js, fjs);}(document, "script", "facebook-jssdk"));</script><div class="fb-video" data-href="https://www.facebook.com/facebook/videos/$5/" data-width="500" data-show-text="false"  data-allowfullscreen="1"><blockquote cite="https://www.facebook.com/facebook/videos/$5/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/facebook/videos/$5/">s</a></blockquote></div>

";s:6:"height";s:3:"385";s:5:"width";s:3:"466";}i:49;a:7:{s:2:"id";s:3:"100";s:5:"title";s:7:"Sendvid";s:7:"website";s:18:"http://sendvid.com";s:10:"regexmatch";s:33:"http://sendvid.com/([A-Za-z0-9]*)";s:9:"embedcode";s:104:"<iframe width="640" height="360" src="//sendvid.com/embed/$1" frameborder="0" allowfullscreen></iframe>
";s:6:"height";s:3:"360";s:5:"width";s:3:"640";}i:50;a:7:{s:2:"id";s:3:"101";s:5:"title";s:14:"Streamable.com";s:7:"website";s:22:"https://streamable.com";s:10:"regexmatch";s:41:"htt(p|ps)://streamable.com/([A-Za-z0-9]*)";s:9:"embedcode";s:257:"<div style="width: 100%; height: 0px; position: relative; padding-bottom: 178.218%;"><iframe src="https://streamable.com/s/$2" frameborder="0" width="100%" height="100%" allowfullscreen style="width: 100%; height: 100%; position: absolute;"></iframe></div>
";s:6:"height";s:3:"360";s:5:"width";s:3:"640";}i:51;a:7:{s:2:"id";s:3:"102";s:5:"title";s:5:"imgur";s:7:"website";s:17:"https://imgur.com";s:10:"regexmatch";s:58:"htt(p|ps)://[A-Za-z\.]*imgur.com/([A-Za-z0-9]*)[\.A-Za-z]*";s:9:"embedcode";s:145:"<blockquote class="imgur-embed-pub" lang="en" data-id="$2"></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
";s:6:"height";s:3:"360";s:5:"width";s:3:"640";}i:52;a:7:{s:2:"id";s:3:"103";s:5:"title";s:16:"Youtube Playlist";s:7:"website";s:19:"https://youtube.com";s:10:"regexmatch";s:57:"htt(p|ps)://www.youtube.com/playlist\?list=([A-Za-z0-9]*)";s:9:"embedcode";s:131:"<iframe width="640" height="360" src="https://www.youtube.com/embed/videoseries?list=$2" frameborder="0" allowfullscreen></iframe>
";s:6:"height";s:3:"360";s:5:"width";s:3:"640";}i:53;a:7:{s:2:"id";s:3:"104";s:5:"title";s:8:"Pastebin";s:7:"website";s:20:"https://pastebin.com";s:10:"regexmatch";s:35:"https://pastebin.com/([A-Za-z0-9]*)";s:9:"embedcode";s:92:"<iframe src="https://pastebin.com/embed_iframe/$1" style="border:none;width:100%"></iframe>
";s:6:"height";s:3:"360";s:5:"width";s:3:"640";}i:54;a:7:{s:2:"id";s:3:"105";s:5:"title";s:9:"Twitch V2";s:7:"website";s:21:"https://www.twitch.tv";s:10:"regexmatch";s:93:"https://go.twitch.tv/videos/([A-Za-z0-9]*)ZSPLITMZhttps://www.twitch.tv/videos/([A-Za-z0-9]*)";s:9:"embedcode";s:153:"<iframe src="https://player.twitch.tv/?autoplay=false&video=$1" frameborder="0" allowfullscreen="true" scrolling="no" width="480" height="600"></iframe>
";s:6:"height";s:3:"378";s:5:"width";s:3:"620";}i:55;a:7:{s:2:"id";s:3:"106";s:5:"title";s:9:"Ted Talks";s:7:"website";s:19:"https://www.ted.com";s:10:"regexmatch";s:41:"https://www.ted.com/talks/([A-Za-z0-9_]*)";s:9:"embedcode";s:128:"<iframe src="https://embed.ted.com/talks/$1" width="480" height="600"  frameborder="0" scrolling="no" allowfullscreen></iframe>
";s:6:"height";s:3:"480";s:5:"width";s:3:"854";}i:56;a:7:{s:2:"id";s:3:"108";s:5:"title";s:7:"Spotify";s:7:"website";s:19:"https://spotify.com";s:10:"regexmatch";s:49:"htt(p|ps)://open.spotify.com/track/([A-Za-z0-9]*)";s:9:"embedcode";s:138:"<iframe src="https://embed.spotify.com/?uri=spotify:track:$2" width="480" height="600" frameborder="0" allowtransparency="true"></iframe>
";s:6:"height";s:2:"80";s:5:"width";s:3:"250";}i:57;a:7:{s:2:"id";s:3:"109";s:5:"title";s:14:"Facebook Posts";s:7:"website";s:20:"https://facebook.com";s:10:"regexmatch";s:69:"htt(p|ps)://([A-Za-z]*).facebook.com/([A-Za-z0-9_\.]*)/posts/([0-9]*)";s:9:"embedcode";s:435:"<div id="fb-root"></div><script>(function(d,s,id){var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.12";fjs.parentNode.insertBefore(js, fjs);}(document, "script", "facebook-jssdk"));</script><div class="fb-post" data-href="https://www.facebook.com/$3/posts/$4/" data-width="500" data-show-text="true"></div>
";s:6:"height";s:3:"500";s:5:"width";s:3:"500";}i:58;a:7:{s:2:"id";s:3:"110";s:5:"title";s:7:"US News";s:7:"website";s:21:"http://www.usnews.com";s:10:"regexmatch";s:76:"htt(p|ps)://www.usnews.com/news/features/news-video?([w.=_&;]+?)videoId=(d+)";s:9:"embedcode";s:253:"<iframe width="590" height="332" src="http://launch.newsinc.com/?type=VideoPlayer/Single&widgetId=1&videoId=$3" frameborder="no" scrolling="no" noresize marginwidth="0" marginheight="0" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe>
";s:6:"height";s:3:"332";s:5:"width";s:3:"590";}i:59;a:7:{s:2:"id";s:3:"114";s:5:"title";s:5:"vbox7";s:7:"website";s:21:"https://www.vbox7.com";s:10:"regexmatch";s:41:"https://www.vbox7.com/play:([A-Za-z0-9]*)";s:9:"embedcode";s:127:"<iframe width="560" height="315" src="https://www.vbox7.com/emb/external.php?vid=$1" frameborder="0" allowfullscreen></iframe>
";s:6:"height";s:3:"315";s:5:"width";s:3:"560";}i:60;a:7:{s:2:"id";s:3:"116";s:5:"title";s:4:"Yarn";s:7:"website";s:0:"";s:10:"regexmatch";s:48:"htt(p|ps)://getyarn.io/yarn-clip/([A-Za-z0-9-]*)";s:9:"embedcode";s:183:"
<iframe seamless="seamless" style="width: 100%; border: none; display: block; max-width: 768px; height: 600px;" src="https://getyarn.io/yarn-clip/embed/$2?autoplay=false"> </iframe>
";s:6:"height";s:3:"600";s:5:"width";s:3:"768";}i:61;a:7:{s:2:"id";s:3:"117";s:5:"title";s:10:"Buzzsprout";s:7:"website";s:0:"";s:10:"regexmatch";s:82:"htt(p|ps)://www.buzzsprout.com/([0-9]*)/([0-9]*)-(([0-9A-Za-z-]*)|([0-9A-Za-z-]*))";s:9:"embedcode";s:77:"
<script src="https://www.buzzsprout.com/$2/$3-$4.js?player=small"></script>
";s:6:"height";s:3:"600";s:5:"width";s:3:"768";}i:62;a:7:{s:2:"id";s:3:"118";s:5:"title";s:6:"TikTok";s:7:"website";s:0:"";s:10:"regexmatch";s:58:"htt(p|ps)://www.tiktok.com/@([0-9A-Za-z_]*)/video/([0-9]*)";s:9:"embedcode";s:326:"
<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@$2/video/$3" data-video-id="$3" style="max-width: 768px;min-width: 600px;" > <section> <a target="_blank" title="@$2" href="https://www.tiktok.com/@$2">@$2</a> <p> </p>&nbsp; </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>
";s:6:"height";s:3:"600";s:5:"width";s:3:"768";}}';
?>